modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

issueTrackerURL="https://github.com/dedouwe26/CreativeTools/issues" #optional

[[mods]] #mandatory

modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory
displayURL="https://github.com/dedouwe26/CreativeTools" #optional
logoFile="${mod_id}.png" #optional

authors="0xDED"

description='''
This is a mod which adds configurable variants of various blocks for creative in Create: Aeronautics.
This includes the Levitite block and the steam vent.
'''

[[mixins]]
config="${mod_id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"